FROM resin/rpi-raspbian:stretch-20180228

ADD . /app
WORKDIR /app

RUN apt-get update -y && \
    apt-get install -y git make && \
    curl -L https://git.io/n-install | bash -s -- -y && \
    source /root/.bashrc && \
    n 8.9.4 && \
    npm install

CMD ["node", "index.js"]